# --------------------------------------------------------------------------------------------------
# Elevator Settings
# --------------------------------------------------------------------------------------------------
BOTTOM_EXTEND_POSITION = 1890
BOTTOM_ROT_POSITION    = 528

LOW_EXTEND_POSITION = 2041
LOW_ROT_POSITION    = 2633

MED_EXTEND_POSITION = 2421
MED_ROT_POSITION    = 804

HIGH_EXTEND_POSITION = 2983
HIGH_ROT_POSITION    = 947

TOP_EXTEND_POSITION = 3045
TOP_ROT_POSITION    = 1107

LAUNCH_POSITION = 1630
HANG_POSITION   = 2326
HUNG_POSITION   = 420

DEFAULT_WORM_POWER     = 0.8
DEFAULT_ELEVATOR_POWER = 0.9
HOMING_POWER           = 0.7

# --------------------------------------------------------------------------------------------------
# Drive Base Settings
# --------------------------------------------------------------------------------------------------

DEAD_ZONE_LOW  = 0.9
DEAD_ZONE_HIGH = 0.9

STRAFE_OFFSET = 1.1

# --------------------------------------------------------------------------------------------------
# Intake Settings
# --------------------------------------------------------------------------------------------------

INTAKE_SPEED  = 1.0
OUTTAKE_SPEED = 1.0

# --------------------------------------------------------------------------------------------------
# Launcher Settings
# --------------------------------------------------------------------------------------------------

LAUNCHER_SERVO_POSITION = 1.0

# --------------------------------------------------------------------------------------------------
# Hanger Settings
# --------------------------------------------------------------------------------------------------

HANGER_SERVO_POSITION = 1.0

# --------------------------------------------------------------------------------------------------
# Misc
# --------------------------------------------------------------------------------------------------

ENDGAME_TRIGGER_SENSITIVITY      = 0.9
PLANE_LAUNCH_TRIGGER_SENSITIVITY = 0.9
